DROP TABLE IF EXISTS CART_ITEM;
DROP TABLE IF EXISTS CART ;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS customers;

CREATE TABLE CART (
	ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE CART_ITEM (
	ID VARCHAR(75),PRODUCT_ID VARCHAR(25),
	CART_ID varchar(50),
	QUANTITY BIGINT,
	CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID),
	
	CONSTRAINT product_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
	
	CONSTRAINT cart_FK FOREIGN KEY (CART_ID) REFERENCES CART(ID)
);

CREATE TABLE `users` (
`username` varchar(16) NOT NULL,
`password` varchar(32) NOT NULL,
`email` varchar(255) DEFAULT NULL,
`create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE PRODUCTS (
	ID VARCHAR(25) PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(250),
	UNIT_PRICE DECIMAL,
	MANUFACTURER VARCHAR(50),
	CATEGORY VARCHAR(50),
	CONDITION VARCHAR(50),
	UNITS_IN_STOCK BIGINT,
	UNITS_IN_ORDER BIGINT,
	DISCONTINUED BOOLEAN
);

CREATE TABLE customers (
	ID VARCHAR(25) PRIMARY KEY,
	NAME VARCHAR(50),
	address  VARCHAR(250),
	noOfOrdersMade INT
);

